services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Tillu#1234
      MYSQL_DATABASE: ecommerce_multi_vendor
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build: 
      context: ./backend-spring boot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce_multi_vendor?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Tillu#1234
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mysql_data:
